name: 🛡️ Dependency Updates

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  security-audit:
    name: Security Audit
    runs-on: windows-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: ⚡ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 📦 Restore dependencies
      working-directory: src
      run: dotnet restore --verbosity minimal

    - name: 🔍 List outdated packages
      working-directory: src
      run: |
        Write-Host "Checking for outdated packages..." -ForegroundColor Blue
        
        try {
          dotnet list package --outdated --verbosity minimal
          Write-Host "Package audit completed." -ForegroundColor Green
        } catch {
          Write-Host "Warning: Could not check for outdated packages." -ForegroundColor Yellow
        }

    - name: 🛡️ Security audit
      working-directory: src
      run: |
        Write-Host "Running security audit..." -ForegroundColor Blue
        
        # Check for known vulnerabilities
        try {
          dotnet list package --vulnerable --include-transitive --verbosity minimal
          
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Security vulnerabilities found!" -ForegroundColor Red
            Write-Host "Please review and update vulnerable packages." -ForegroundColor Yellow
          } else {
            Write-Host "No known vulnerabilities found." -ForegroundColor Green
          }
        } catch {
          Write-Host "Warning: Could not complete security audit." -ForegroundColor Yellow
        }

    - name: 📋 Generate audit report
      working-directory: src
      run: |
        Write-Host "Generating dependency audit report..." -ForegroundColor Blue
        
        # Create a simple report
        $reportFile = "../dependency-audit-report.txt"
        
        "Dependency Audit Report" | Out-File $reportFile
        "Generated: $(Get-Date)" | Add-Content $reportFile
        "=" * 50 | Add-Content $reportFile
        "" | Add-Content $reportFile
        
        "Installed Packages:" | Add-Content $reportFile
        "-" * 20 | Add-Content $reportFile
        
        try {
          dotnet list package --verbosity quiet | Add-Content $reportFile
        } catch {
          "Could not list packages." | Add-Content $reportFile
        }
        
        "" | Add-Content $reportFile
        "Outdated Packages:" | Add-Content $reportFile
        "-" * 18 | Add-Content $reportFile
        
        try {
          dotnet list package --outdated --verbosity quiet | Add-Content $reportFile
        } catch {
          "Could not check for outdated packages." | Add-Content $reportFile
        }
        
        "" | Add-Content $reportFile
        "Security Vulnerabilities:" | Add-Content $reportFile
        "-" * 25 | Add-Content $reportFile
        
        try {
          dotnet list package --vulnerable --include-transitive --verbosity quiet | Add-Content $reportFile
        } catch {
          "Could not check for vulnerabilities." | Add-Content $reportFile
        }
        
        Write-Host "Audit report generated: $reportFile" -ForegroundColor Green

    - name: 📂 Upload audit report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-audit-report
        path: dependency-audit-report.txt
        retention-days: 30