name: Dependency Updates

on:
  schedule:
    # Run weekly on Sundays at 6:00 AM UTC
    - cron: '0 6 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  security-audit:
    name: Security Audit
    runs-on: windows-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        working-directory: ./src
        run: dotnet restore idasen-desk-core.sln --verbosity minimal

      - name: List Packages
        working-directory: ./src
        shell: pwsh
        run: |
          Write-Host "=== NuGet Package Audit ===" -ForegroundColor Green
          dotnet list package --outdated --include-transitive
          
      - name: Check for Vulnerable Packages
        working-directory: ./src
        shell: pwsh
        run: |
          Write-Host "=== Security Vulnerability Check ===" -ForegroundColor Green
          dotnet list package --vulnerable --include-transitive
          
          # Note: This command will return exit code 0 even if vulnerabilities are found
          # We should manually review the output

  dependency-review:
    name: Dependency Review
    runs-on: windows-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          config-file: './.github/dependency-review-config.yml'
          fail-on-severity: moderate